export const INITIAL_WALLET_AMOUNT = 200;
export const ONE_TRANSACTION_AMOUNT = 100;
export const BITCOIN_TRANSACTION_AMOUNT = 1;
export const BITCOIN_PRICE_RANGE = 1000;
export const INITIAL_BITCOIN_PRICE = 1000;
export const BITCOIN_PRICE_DEMARCATION_LEVEL = 10000;
