// wallet
export const DEPOSIT_WALLET = 'DEPOSIT_WALLET';
export const WITHDRAWAL_WALLET = 'WITHDRAWAL_WALLET';
export const DECREASE_WALLET_AFTER_BUY = 'DECREASE_WALLET_AFTER_BUY';
export const INCREASE_WALLET_AFTER_SELL = 'INCREASE_WALLET_AFTER_SELL';

// bitcoin
export const PURCHASE_BITCOIN = 'PURCHASE_BITCOIN';
export const SELL_BITCOIN = 'SELL_BITCOIN';
export const INCREASE_BITCOIN_PRICE = 'INCREASE_BITCOIN_PRICE';
export const DECREASE_BITCOIN_PRICE = 'DECREASE_BITCOIN_PRICE';

// history
export const ADD_EVENT_TO_HISTORY = 'ADD_EVENT_TO_HISTORY';
